-- MySQL Script generated by MySQL Workbench
-- Thu Jan 29 13:13:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Task1_Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Task1_Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Task1_Optica` DEFAULT CHARACTER SET utf8 ;
USE `Task1_Optica` ;

-- -----------------------------------------------------
-- Table `Task1_Optica`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`adress` (
  `adress_id` INT NOT NULL,
  `street` VARCHAR(20) NOT NULL,
  `number` INT NOT NULL,
  `floor` VARCHAR(20) NULL,
  `door` VARCHAR(10) NULL,
  `city` VARCHAR(30) NOT NULL,
  `zip_code` VARCHAR(15) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`adress_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task1_Optica`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`supplier` (
  `supplier_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` BIGINT NOT NULL,
  `fax_number` BIGINT NULL,
  `nif` VARCHAR(10) NOT NULL,
  `adress_id` INT NULL AUTO_INCREMENT,
  UNIQUE INDEX `nif_id_UNIQUE` (`nif` ASC) VISIBLE,
  PRIMARY KEY (`supplier_id`),
  INDEX `fk_supplier_adress_idx` (`adress_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_adress`
    FOREIGN KEY (`adress_id`)
    REFERENCES `Task1_Optica`.`adress` (`adress_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task1_Optica`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`brand` (
  `brand_id` INT NOT NULL,
  `supplier_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brand_id`),
  INDEX `fk_brand_supplier_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_brand_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Task1_Optica`.`supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task1_Optica`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`glasses` (
  `glasses_id` INT NULL,
  `graduation_left` DECIMAL(4,2) NOT NULL,
  `graduation_right` DECIMAL(4,2) NOT NULL,
  `material_type` ENUM('rimless', 'acetate', 'metallic') NOT NULL,
  `material_color` VARCHAR(45) NOT NULL,
  `glass_right_color` VARCHAR(45) NOT NULL,
  `glass_left_color` VARCHAR(45) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`glasses_id`),
  INDEX `fk_glasses_brand_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `Task1_Optica`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task1_Optica`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`customers` (
  `customers_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adress_id` INT NOT NULL,
  `phone_number` BIGINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registration_date` DATE NOT NULL,
  `customer_recomender_id` INT NOT NULL,
  PRIMARY KEY (`customers_id`),
  INDEX `fk_customer_recomender_idx` (`customer_recomender_id` ASC) VISIBLE,
  INDEX `fk_customers_adress_idx` (`adress_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_recomender`
    FOREIGN KEY (`customer_recomender_id`)
    REFERENCES `Task1_Optica`.`customers` (`customers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_adress`
    FOREIGN KEY (`adress_id`)
    REFERENCES `Task1_Optica`.`adress` (`adress_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task1_Optica`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`worker` (
  `worker_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`worker_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task1_Optica`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task1_Optica`.`sale` (
  `sale_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  `worker_id` INT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sale_worker_idx` (`worker_id` ASC) VISIBLE,
  INDEX `fk_sale_glasses_idx` (`glasses_id` ASC) VISIBLE,
  INDEX `fk_sale_customers_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_worker`
    FOREIGN KEY (`worker_id`)
    REFERENCES `Task1_Optica`.`worker` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_glasses`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `Task1_Optica`.`glasses` (`glasses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Task1_Optica`.`customers` (`customers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
